"""empty message

Revision ID: d81a57864cd6
Revises: 03b9cee4f337
Create Date: 2017-06-01 10:46:46.295581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd81a57864cd6'
down_revision = '03b9cee4f337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('station_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('river_basin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('water_level', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='info_pkey')
    )
    # ### end Alembic commands ###
